name: Java pipeline

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: intervenction
        ports:
          - 3306:3306

    steps:
      - name: Recuperation du code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: maven

      - name: Installation des dépendances
        run: mvn package

      - name: Build avec options de débogage
        run: mvn clean install -x

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Java artifact
          path: target/intervention-0.0.1-SNAPSHOT.jar
